= Support
:page-authors: gdams, karianna, sxa, tellison, SueChaplain, sxa555, mvitz, ParkerM, M-Davies, Malax, lasombra, practicalli-john, jeffalder, hendrikebbers, douph1, andrew-m-leonard, mr-david-owens, DanHeidinga

== Community Support

Read https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b[Java Is Still Free (3.0.0)] for some background information about Java
support options. We are prepared to stand behind our release quality
binaries, so each build that is identified as a release receives support
via the Adoptium community. Our support means that you can raise an
issue to describe a bug you have found in the build, and we will work
with you and the appropriate development team to resolve it. Any fixes
we identify will be delivered as part of the next Adoptium release.

As a community of open source developers, our commitment is to triage
any issues raised and champion them in the appropriate source code
project. Of course, if the problem arises from the way we build and test
the code we can fix that directly. For higher levels of assurance you
should contact commercial companies offering support.

== Release Roadmap

The frequency of Adoptium releases is guided by the schedule of our
dependencies.

OpenJDK provide a new feature release every six months, and a
maintenance/security update based upon each active release every three
months. The release dates for those from the OpenJDK project are the
https://www.oracle.com/security-alerts/[Tuesdays closest to the 17th] of
January, April, July and October. We will follow this schedule for
publishing binary releases from Adoptium to ensure you get the latest,
most secure builds.

In addition, every two years after Java 17's release one feature release
will be designated as a Long Term Supported (LTS) release. We will
produce LTS releases for at least four years. This assurance will allow
you to stay on a well-defined code stream, and give you time to migrate
to the next, new, stable, LTS release when it becomes available.

Based upon this roadmap, and starting with Java 8 (currently supported
releases in bold) here is the timetable for the various releases. Note
that specific release dates in here are the ones from the OpenJDK source
project and may not match when the Adoptium project will have binaries
available - there will usually be a delay while we complete our
extensive build and tests cycles.

include::_partials/support-table.adoc[]

^[1]^ As a general philosophy, Adoptium will continue to build binaries
for LTS releases as long as the corresponding upstream source is
actively maintained.
