name: Linter

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # for github/super-linter/slim to mark status of each linter run

    steps:
      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: github/super-linter/slim@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Markdown lint complains about the issue templates
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/*
          VALIDATE_YAML: false
